version: "2.1"

networks:
  passec:

services:
  passec-app:
    container_name: passec
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      passec-db:
        condition: service_started
    ports:
      - "18081:8080"
    networks:
      - passec
    env_file:
      - .env

  passec-db:
    image: mariadb:latest
    container_name: passec-db
    ports:
      - "13307:3306"
    env_file:
      - .env
    networks:
      - passec
